version: '3.5'

services:
  traefik:
    image: traefik
    command: 
      --api \
      --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik.kb \
      --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
    networks:
      - proxy

networks:
  proxy:
    external: true


